language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
before_install:
  - wget http://www.ip2location.com/downloads/sample.bin.db24.zip
  - unzip sample.bin.db24.zip '*.BIN'
  - wget http://www.ip2location.com/downloads/sample6.bin.db24.zip
  - unzip sample6.bin.db24.zip '*.BIN'
