sudo: false
language: node_js

os:
  - osx
  - linux

node_js: [6, 7, 8, 9, 10, 11, 12]
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

osx_image: xcode8

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then CXX=g++-4.9; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then CXX=g++; fi # g++ is an alias of clang, so let's use it
  # print versions
  - node --version
  - npm --version
  - $CXX --version
  # download and extract sample databases
  - wget http://www.ip2location.com/downloads/sample.bin.db24.zip
  - unzip sample.bin.db24.zip '*.BIN'
  - wget http://www.ip2location.com/downloads/sample6.bin.db24.zip
  - unzip sample6.bin.db24.zip '*.BIN'

install:
  - npm install --build-from-source

script:
  - npm test
